# Generated by Django 5.0.4 on 2025-05-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SupportManage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите имя менеджера",
                        max_length=100,
                        verbose_name="Имя менеджера",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Укажите почту",
                        max_length=254,
                        unique=True,
                        verbose_name="Почта",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Укажите тлф",
                        max_length=35,
                        null=True,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "tg_nick",
                    models.CharField(
                        blank=True,
                        help_text="Укажите ник",
                        max_length=35,
                        null=True,
                        verbose_name="TG ник",
                    ),
                ),
                (
                    "date_born",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату рождения",
                        null=True,
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="supports/avatars",
                        verbose_name="Аватар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support(Менеджер)",
                "verbose_name_plural": "Supports(Менеджеры)",
            },
        ),
    ]
